### ISSUE TITLE
Error when run both master and dev branch

### ISSUE THREAD

**Issue by rlonka** [majeau-bettez/ecospold2matrix#6]
`
>>> import ecospold2matrix as e2m
>>> parser = e2m.Ecospold2Matrix('/home/radekl/Desktop/ecoinvent 3.4_cutoff_lci_ecoSpold02/datasets', project_name='eco34', out_dir='/home/radekl/eco_matrices', positive_waste=True)
2018-02-22 10:58:36,955 - eco34 - INFO - Ecospold2Matrix Processing
2018-02-22 10:58:36,961 - eco34 - INFO - Current git commit: ca2593a74f2bd7c769bbeea365b915a89a8c9c3d
2018-02-22 10:58:36,962 - eco34 - INFO - Project name: eco34
2018-02-22 10:58:36,962 - eco34 - INFO - Unit process and Master data directory: /home/radekl/Desktop/ecoinvent 3.4_cutoff_lci_ecoSpold02/datasets
2018-02-22 10:58:36,962 - eco34 - INFO - Data saved in: /home/radekl/eco_matrices
2018-02-22 10:58:36,962 - eco34 - INFO - Sign conventions changed to make waste flows positive
2018-02-22 10:58:36,962 - eco34 - INFO - Pickle intermediate results to files
2018-02-22 10:58:36,962 - eco34 - INFO - Order processes based on: ISIC, activityName
2018-02-22 10:58:36,962 - eco34 - INFO - Order elementary exchanges based on: comp, name, subcomp
2018-02-22 10:58:36,972 - eco34 - WARNING - Could not establish connection to database
>>> parser.ecospold_to_Leontief(with_absolute_flows=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radekl/workspace/ecospold2matrix/ecospold2matrix/ecospold2matrix.py", line 363, in ecospold_to_Leontief
    self.extract_products()
  File "/home/radekl/workspace/ecospold2matrix/ecospold2matrix/ecospold2matrix.py", line 669, in extract_products
    assert os.path.exists(fp), "Can't find " + self.__INTERMEXCHANGE
AssertionError: Can't find IntermediateExchanges.xml
>>> 
`

**Comment by MaximeAgez** [comment]
Hi,
I think this error is popping because you did not unzip the .7z file from the ecoinvent website. Hence why it does not find the IntermediateExchanges.xml file.
